//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckItem()
        {
            this.IsComputer = 0;
        }
    
        public int Id { get; set; }
        public int CheckId { get; set; }
        public string ItemId { get; set; }
        public byte IsComputer { get; set; }
    
        public virtual Check Check { get; set; }
    }
}
