//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputersShopContainer1 : DbContext
    {
        public ComputersShopContainer1()
            : base("name=ComputersShopContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Component> Component { get; set; }
        public virtual DbSet<Computer> Computer { get; set; }
        public virtual DbSet<ComputerItem> ComputerItem { get; set; }
        public virtual DbSet<Buyer> Buyer { get; set; }
        public virtual DbSet<Check> Check { get; set; }
        public virtual DbSet<CheckItem> CheckItem { get; set; }
    }
}
